---
- hosts: allservers
  roles: 
  - pre_install
  tags: pre

- hosts: db
  roles:
  - maria_db
  tags: db

- hosts: monitoring
  roles:
  - nagios
  tags: monitor
  
- hosts: apps, db, lb
  roles:
  - nrpe
  tags: nrpe

- hosts: apps
  roles:
  - kanboard
  tags: app

- hosts: lb
  roles:
  - lb
  tags: lb

# - hosts: loki
#   roles:
#   - grafana_loki
#   tags: loki
- hosts: apps, db, lb, monitoring, loki
  roles: 
  - promtail
  tags: prom